# Generated by Django 6.0.4 on 2026-04-26 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rental_guarantee_info_rental_total_paid_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte')], default='CC', max_length=5)),
                ('doc_id', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('phone_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('name_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, choices=[('nequi', 'Nequi'), ('bancolombia', 'Bancolombia'), ('daviplata', 'Daviplata'), ('banco_bogota', 'Banco de Bogotá'), ('otro', 'Otro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transaccion', 'Transacción / Transferencia')], default='efectivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reservado'), ('preparing', 'Alistado'), ('ready', 'Listo para Entrega'), ('delivered', 'Entregado'), ('received', 'Recibido'), ('overdue', 'Atrasado')], default='reserved', max_length=20),
        ),
        migrations.AddField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='api.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='api.customer'),
        ),
    ]
