# Generated by Django 6.0.4 on 2026-04-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_payment_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='label',
            field=models.CharField(default='Pago', max_length=100),
        ),
    ]
