# Generated by Django 6.0.4 on 2026-04-26 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_payment_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_rental_daily',
            new_name='price_rental',
        ),
        migrations.RenameField(
            model_name='rentalitem',
            old_name='price_per_day_at_rental',
            new_name='price_at_rental',
        ),
    ]
