# Generated by Django 6.0.4 on 2026-04-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_price_rental_daily_product_price_rental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pieces_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Talla o Medida', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('sale', 'Venta'), ('rental', 'Alquiler'), ('both', 'Venta y Alquiler')], default='sale', max_length=10),
        ),
    ]
