# Generated by Django 6.0.4 on 2026-04-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_color_product_pieces_count_product_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Urban Luxury', max_length=200)),
                ('hero_title', models.CharField(default='URBAN LUXURY', max_length=255)),
                ('hero_tagline', models.CharField(default='ESTILO SIN LÍMITES', max_length=255)),
                ('hero_subtitle', models.TextField(default='ALQUILER Y VENTA DE ALTA COSTURA PARA EVENTOS EXCLUSIVOS. EL LUJO QUE MERECES, SIN COMPROMISOS.')),
                ('about_text', models.TextField(default='En Urban Luxury, redefinimos la experiencia de vestir bien. Creemos que la elegancia no debería ser una carga, sino una elección libre y flexible.')),
                ('about_vision', models.TextField(default='Convertirnos en el referente nacional de moda circular de lujo, promoviendo un estilo de vida sofisticado y sostenible.')),
                ('about_mission', models.TextField(default='Facilitar el acceso a prendas exclusivas mediante un servicio impecable de alquiler y venta, garantizando que cada cliente se sienta su mejor versión.')),
                ('contact_phone', models.CharField(default='+57 300 000 0000', max_length=50)),
                ('contact_email', models.EmailField(default='info@urbanluxury.com', max_length=254)),
                ('contact_address', models.CharField(default='Avenida Lujo #45-12, Ciudad', max_length=255)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('tiktok_url', models.URLField(blank=True, null=True)),
                ('whatsapp_url', models.URLField(blank=True, null=True)),
                ('footer_text', models.TextField(default='© 2026 Urban Luxury. Todos los derechos reservados.')),
            ],
        ),
    ]
