# Generated by Django 6.0.4 on 2026-04-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_siteconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_title_gold',
            field=models.CharField(default='LUXURY', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_title_white',
            field=models.CharField(default='URBAN', max_length=100),
        ),
    ]
