# Generated by Django 6.0.4 on 2026-04-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_siteconfig_hero_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='company_name',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='company_name_gold',
            field=models.CharField(default='LUXURY', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='company_name_white',
            field=models.CharField(default='URBAN', max_length=100),
        ),
    ]
