# Generated by Django 6.0.4 on 2026-04-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_siteconfig_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='theme',
            field=models.CharField(choices=[('noir', 'Urban Noir (Oscuro/Oro)'), ('arctic', 'Minimal Arctic (Claro/Plata)'), ('cyber', 'Street Cyber (Oscuro/Neon)')], default='noir', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='typography',
            field=models.CharField(choices=[('modern', 'Modern Clean (Outfit)'), ('classic', 'Classic Editorial (Playfair)'), ('tech', 'Urban Tech (Space Grotesk)')], default='modern', max_length=20),
        ),
    ]
