# Generated by Django 6.0.4 on 2026-04-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_siteconfig_theme_siteconfig_typography'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='guarantee_type',
            field=models.CharField(choices=[('documento', 'Documento'), ('monto', 'Monto Efectivo'), ('otro', 'Otro')], default='documento', max_length=20),
        ),
    ]
