# Generated by Django 6.0.4 on 2026-04-27 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rental_guarantee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=5)),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('transaccion', 'Transacción / Transferencia')], default='efectivo', max_length=50)),
                ('bank', models.CharField(blank=True, choices=[('nequi', 'Nequi'), ('bancolombia', 'Bancolombia'), ('daviplata', 'Daviplata'), ('banco_bogota', 'Banco de Bogotá'), ('otro', 'Otro')], max_length=50, null=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
